// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="AI Assistant"
          text="Not Sure What Style to Get? Let our AI Braid Bestie help you discover the perfect braiding style based on your hair, lifestyle, and vibe."
          primaryButton={{
            text: "Talk to Braid Bestie",
            href: "#",
          }}
          secondaryButton={{
            text: "View All Styles",
            href: "#trending",
          }}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
