// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSimple from '@/components/sections/faq/FaqSimple';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSimple
          tag="Help"
          title="Common Questions"
          description="We've got you covered."
          items={[
            {
              question: "How do I book an appointment?",
              answer: "Click 'Book This Style' on any card and follow the prompts.",
            },
            {
              question: "Can I request custom styles?",
              answer: "Yes, chat with our Braid Bestie to discuss your vision.",
            },
            {
              question: "What hair type works best?",
              answer: "Our AI helps find styles customized to any hair type.",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
