/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import AvatarGroup from "@/components/ui/AvatarGroup";
import Input from "@/components/ui/Input";

const primaryButton = {
  text: "Explore Styles",
  href: "#trending"
};
const secondaryButton = {
  text: "Chat with Bestie",
  href: "#contact"
};

type HeroBillboardProps = {
  tag?: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  avatarsSrc?: string[];
  avatarsLabel?: string;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section aria-label="Hero section" className="relative pt-25 pb-20 md:pt-30">
      <HeroBackgroundSlot />
      <div className="flex flex-col gap-12 md:gap-15 w-content-width mx-auto">
        <div className="flex flex-col items-center gap-3 text-center">
          {undefined && undefined.length > 0 ? (
            <AvatarGroup className="mb-1" />
          ) : "✨ Now Booking Spring Styles" ? (
            <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
              <p>{"✨ Now Booking Spring Styles"}</p>
            </div>
          ) : null}

          <TextAnimation
            text={"Your [Dream] Braids Await"}
            variant={"slide-up"}
            gradientText={true}
            tag="h1"
            className="md:max-w-8/10 text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Discover gorgeous braiding styles and book your next look — all in one place."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance"
          />

          <form className="flex flex-col sm:flex-row justify-center items-center gap-3 mt-4 md:mt-6 w-full max-w-2xl mx-auto" onSubmit={(e) => e.preventDefault()}>
            <Input type="email" placeholder="Email address" className="w-full sm:w-auto flex-1" required />
            <Input type="tel" placeholder="Phone number" className="w-full sm:w-auto flex-1" required />
            <Button text="Sign Up" variant="primary" className="w-full sm:w-auto" />
          </form>
        </div>

        <ScrollReveal variant="fade" delay={0.2} className="w-full p-2 xl:p-3 2xl:p-4 card rounded overflow-hidden">
          <ImageOrVideo imageSrc={"https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785631272160-bz62ywud.jpg"} className="aspect-4/5 md:aspect-video" />
        </ScrollReveal>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
