// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboard
          tag="✨ Now Booking Spring Styles"
          title="Your [Dream] Braids Await"
          description="Discover gorgeous braiding styles, get AI-powered recommendations from our Braid Bestie, and book your next look — all in one place."
          primaryButton={{
            text: "Explore Styles",
            href: "#trending",
          }}
          secondaryButton={{
            text: "Chat with Bestie",
            href: "#contact",
          }}
          imageSrc="https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785631272160-bz62ywud.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
