// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboard from '@/components/sections/hero/HeroBillboard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBillboard
          tag="✨ Now Booking Spring Styles"
          title="Your [Dream] Braids Await"
          description="Discover gorgeous braiding styles, get AI-powered recommendations from our Braid Bestie, and book your next look — all in one place."
          primaryButton={{
            text: "Explore Styles",
            href: "#trending",
          }}
          secondaryButton={{
            text: "Chat with Bestie",
            href: "#contact",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/dreamy-young-woman-with-bright-makeup-posing-with-pleasure-close-up-photo-gorgeous-female-model-pink-periwig-looking-with-smile_197531-8034.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
