// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "trending" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TrendingSection(): React.JSX.Element {
  return (
    <div id="trending" data-section="trending">
        <SectionErrorBoundary name="trending">
              <FeaturesRevealCardsBento
          tag="Trending ✨"
          title="Most Requested Looks"
          description="Discover your next signature style."
          items={[
            {
              title: "Knotless Braids",
              description: "Pain-free, lightweight. Advanced.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785632857115-p03lzhgg.jpg",
            },
            {
              title: "Box Braids",
              description: "Classic look, versatile. Medium.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/lovely-african-american-woman-with-dreadlocks-leopard-outfit-cafe-beautiful-cool-fashionable-black-young-girl-indoor_627829-4832.jpg",
            },
            {
              title: "Cornrows",
              description: "Clean, defined patterns. Medium.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785632674301-fgcvf9ea.jpg",
            },
            {
              title: "Goddess Braids",
              description: "Flowy, glam vibes. Advanced.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785632620676-5kko0li0.jpg",
            },
            {
              title: "Fulani Braids",
              description: "Intricate, cultural style. Advanced.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785632418338-r4kvnuz4.jpg",
            },
            {
              title: "Twists",
              description: "Soft and bouncy. Easy.",
              href: "#contact",
              imageSrc: "https://storage.googleapis.com/webild/users/user_3H6bWYFe0S1ZtUhWnfj8Arfxk1E/uploaded-1785632573620-y5p65qt4.jpg",
            },
            {
              title: "Bohemian Braids",
              description: "Textured, effortless. Medium.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-with-turquoise-hair-striped-dress-posing_24972-2937.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
