// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "trending" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TrendingSection(): React.JSX.Element {
  return (
    <div id="trending" data-section="trending">
        <SectionErrorBoundary name="trending">
              <FeaturesRevealCardsBento
          tag="Trending ✨"
          title="Most Requested Looks"
          description="Discover your next signature style."
          items={[
            {
              title: "Knotless Braids",
              description: "Pain-free, lightweight. Advanced.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/young-stylish-woman-with-pink-purple-braids-black-waist-bag-posing-outdoor_343596-2035.jpg",
            },
            {
              title: "Box Braids",
              description: "Classic look, versatile. Medium.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/lovely-african-american-woman-with-dreadlocks-leopard-outfit-cafe-beautiful-cool-fashionable-black-young-girl-indoor_627829-4832.jpg",
            },
            {
              title: "Cornrows",
              description: "Clean, defined patterns. Medium.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-beautiful-woman-with-braids_23-2151429512.jpg",
            },
            {
              title: "Goddess Braids",
              description: "Flowy, glam vibes. Advanced.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-woman-with-african-braids_633478-1408.jpg",
            },
            {
              title: "Fulani Braids",
              description: "Intricate, cultural style. Advanced.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/individual-with-dreads-rastafari-movement_23-2151712145.jpg",
            },
            {
              title: "Twists",
              description: "Soft and bouncy. Easy.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/beauty-woman-portrait-street-outdoor-portrait-fashion-model_1296-881.jpg",
            },
            {
              title: "Bohemian Braids",
              description: "Textured, effortless. Medium.",
              href: "#contact",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-with-turquoise-hair-striped-dress-posing_24972-2937.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
